CREATE TABLE IF NOT EXISTS positions
(
    position_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(64)                             NOT NULL UNIQUE,
    CONSTRAINT pk_positions PRIMARY KEY (position_id)
);

CREATE TABLE IF NOT EXISTS branches
(
    branch_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(64)                             NOT NULL UNIQUE,
    address   VARCHAR(300)                            NOT NULL,
    CONSTRAINT pk_branches PRIMARY KEY (branch_id)
);

CREATE TABLE IF NOT EXISTS employees
(
    employee_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_name VARCHAR(64)                             NOT NULL,
    surname       VARCHAR(64)                             NOT NULL,
    position_id   BIGINT                                  NOT NULL,
    branch_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (employee_id),
    CONSTRAINT fk_employees_on_positions FOREIGN KEY (position_id) REFERENCES positions (position_id),
    CONSTRAINT fk_employees_on_branches FOREIGN KEY (branch_id) REFERENCES branches (branch_id)
);

CREATE TABLE IF NOT EXISTS services
(
    service_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(150)                            NOT NULL,
    description VARCHAR(2000),
    price       DECIMAL(2)                              NOT NULL,
    CONSTRAINT pk_services PRIMARY KEY (service_id)
);

CREATE TABLE IF NOT EXISTS auto_parts_sections
(
    auto_parts_section_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                 VARCHAR(150)                            NOT NULL UNIQUE,
    CONSTRAINT pk_auto_parts_sections PRIMARY KEY (auto_parts_section_id)
);

CREATE TABLE IF NOT EXISTS auto_parts
(
    auto_part_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                 VARCHAR(150)                            NOT NULL,
    description           VARCHAR(5000),
    purchase_price        DECIMAL(2)                              NOT NULL,
    selling_price         DECIMAL(2)                              NOT NULL,
    auto_parts_section_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_auto_parts PRIMARY KEY (auto_part_id),
    CONSTRAINT fk_auto_parts_on_auto_parts_sections FOREIGN KEY (auto_parts_section_id)
        REFERENCES auto_parts_sections (auto_parts_section_id)
);

CREATE TABLE IF NOT EXISTS clients
(
    client_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_name    VARCHAR(64)                             NOT NULL,
    client_surname VARCHAR(64)                             NOT NULL,
    date_of_birth  DATE,
    CONSTRAINT pk_clients PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS cars
(
    car_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id   BIGINT                                  NOT NULL,
    car_number VARCHAR(30)                             NOT NULL,
    brand      VARCHAR(30)                             NOT NULL,
    model      VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_cars PRIMARY KEY (car_id),
    CONSTRAINT fk_cars_on_clients FOREIGN KEY (owner_id) REFERENCES clients (client_id)
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id  BIGINT                                  NOT NULL,
    client_id    BIGINT                                  NOT NULL,
    car_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_on_employees FOREIGN KEY (employee_id) REFERENCES employees (employee_id),
    CONSTRAINT fk_orders_on_clients FOREIGN KEY (client_id) REFERENCES clients (client_id),
    CONSTRAINT fk_orders_on_cars FOREIGN KEY (car_id) REFERENCES cars (car_id)
);

CREATE TABLE IF NOT EXISTS order_services
(
    order_id   BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    CONSTRAINT pk_order_services PRIMARY KEY (order_id, service_id),
    CONSTRAINT fk_order_services_on_orders FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_order_services_on_services FOREIGN KEY (service_id) REFERENCES services (service_id)
);

CREATE TABLE IF NOT EXISTS order_auto_parts
(
    order_id     BIGINT NOT NULL,
    auto_part_id BIGINT NOT NULL,
    CONSTRAINT fk_order_auto_parts_on_orders FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_order_auto_parts_on_auto_parts FOREIGN KEY (auto_part_id) REFERENCES auto_parts (auto_part_id)
);


